# Generated by Django 3.2.9 on 2021-12-03 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('idaula', models.IntegerField(db_column='IdAula', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idcarrera', models.IntegerField(db_column='IdCarrera', primary_key=True, serialize=False)),
                ('nombrecarrera', models.CharField(blank=True, db_column='NombreCarrera', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('iddocente', models.IntegerField(db_column='IdDocente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=25, null=True)),
                ('apellidop', models.CharField(blank=True, db_column='ApellidoP', max_length=25, null=True)),
                ('apellidom', models.CharField(blank=True, db_column='ApellidoM', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idestudiante', models.IntegerField(db_column='IdEstudiante', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=25, null=True)),
                ('apellidop', models.CharField(blank=True, db_column='ApellidoP', max_length=25, null=True)),
                ('apellidom', models.CharField(blank=True, db_column='ApellidoM', max_length=25, null=True)),
                ('nocontrol', models.IntegerField(blank=True, db_column='NoControl', null=True)),
                ('idcarrera', models.ForeignKey(blank=True, db_column='IdCarrera', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idmateria', models.IntegerField(db_column='IdMateria', primary_key=True, serialize=False)),
                ('nombremateria', models.CharField(blank=True, db_column='NombreMateria', max_length=25, null=True)),
                ('nivel', models.IntegerField(blank=True, db_column='Nivel', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idperiodo', models.IntegerField(db_column='IdPeriodo', primary_key=True, serialize=False)),
                ('periodo', models.CharField(blank=True, db_column='Periodo', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('foliopago', models.IntegerField(db_column='FolioPago', primary_key=True, serialize=False)),
                ('fechapago', models.DateField(blank=True, db_column='FechaPago', null=True)),
                ('fechasist', models.DateField(blank=True, db_column='FechaSist', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=10, null=True)),
                ('usuario', models.CharField(blank=True, db_column='Usuario', max_length=25, null=True)),
                ('idestudiante', models.ForeignKey(blank=True, db_column='IdEstudiante', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.estudiante')),
                ('idmateria', models.ForeignKey(blank=True, db_column='IdMateria', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.materia')),
                ('idperiodo', models.ForeignKey(blank=True, db_column='IdPeriodo', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.periodo')),
            ],
        ),
    ]
