# Generated by Django 3.2.9 on 2021-12-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0002_det_grupo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='idaula',
            field=models.AutoField(db_column='IdAula', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='idcarrera',
            field=models.AutoField(db_column='IdCarrera', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docente',
            name='iddocente',
            field=models.AutoField(db_column='IdDocente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='idestudiante',
            field=models.AutoField(db_column='IdEstudiante', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idgrupo',
            field=models.AutoField(db_column='IdGrupo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materia',
            name='idmateria',
            field=models.AutoField(db_column='IdMateria', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='foliopago',
            field=models.AutoField(db_column='FolioPago', primary_key=True, serialize=False),
        ),
    ]
