# Generated by Django 3.2.9 on 2022-01-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0003_auto_20211210_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='det_grupo',
            options={'verbose_name': 'Detalle_Grupo', 'verbose_name_plural': 'Detalles_Grupos'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, db_column='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pagocurso',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pagomaterial',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechasist',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaSist'),
        ),
    ]
