# Generated by Django 3.2.9 on 2022-01-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0004_auto_20220112_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, db_column='Correo Electrónico', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
