# Generated by Django 3.2.9 on 2022-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0005_auto_20220113_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
