# Generated by Django 3.2.9 on 2022-01-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0006_grupo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
