# Generated by Django 3.2.9 on 2022-01-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0007_docente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
