# Generated by Django 3.2.9 on 2022-01-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0008_pago_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='status',
            field=models.IntegerField(db_column='Status', default='1'),
        ),
    ]
