# Generated by Django 3.2.9 on 2022-02-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0012_auto_20220209_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.RemoveField(
            model_name='pago',
            name='status',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='idperiodo',
            field=models.AutoField(db_column='IdPeriodo', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='idestado',
            field=models.ForeignKey(blank=True, db_column='idestado', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.estado'),
        ),
    ]
