# Generated by Django 3.2.9 on 2022-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0013_auto_20220211_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(blank=True, db_column='Estado', default='Pendiente', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.CharField(blank=True, db_column='Usuario', max_length=25, null=True),
        ),
    ]
